project_id = "vtdyporxyooueriolvvp"

[auth]
enable_signup = true
enable_anonymous_sign_ins = true
site_url = "http://localhost:5173"
additional_redirect_urls = [
	"http://localhost:5173/**",
	"http://127.0.0.1:5173/**",
]